import pg from "pg";const{Pool}=pg;const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==="production"?{rejectUnauthorized:false}:undefined});
export const pgstore={
 async createInvitation(v){await pool.query(`INSERT INTO nrr_invitations(id,token_hash,language,expires_at,login_limit,login_count,status,label,created_at,created_by,approved_by,email,full_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)`,[v.id,v.tokenHash,v.language,v.expiresAt,v.loginLimit,v.loginCount,v.status,v.label,v.createdAt,v.createdBy||null,v.approvedBy||null,v.email||'',v.fullName||v.label||'']);return v},
 async invitationByHash(h){const{rows}=await pool.query("SELECT * FROM nrr_invitations WHERE token_hash=$1",[h]);const x=rows[0];return x?{id:x.id,tokenHash:x.token_hash,language:x.language,expiresAt:x.expires_at,loginLimit:x.login_limit,loginCount:x.login_count,status:x.status,label:x.label,email:x.email,fullName:x.full_name,createdAt:x.created_at}:null},
 async redeemInvitation(h,ipHash){const{rows}=await pool.query("UPDATE nrr_invitations SET login_count=login_count+1,access_ip_hash=COALESCE(access_ip_hash,$2) WHERE token_hash=$1 AND status='active' AND expires_at>now() AND (login_limit IS NULL OR login_count<login_limit) AND (access_ip_hash IS NULL OR access_ip_hash=$2) RETURNING *",[h,ipHash]);const x=rows[0];return x?{id:x.id,language:x.language,expiresAt:x.expires_at,email:x.email,fullName:x.full_name,label:x.label}:null},
 async setGeo(id,geo){await pool.query(`UPDATE nrr_invitations SET geo_country_code=COALESCE(geo_country_code,$2),geo_country_name=COALESCE(geo_country_name,$3),geo_region=COALESCE(geo_region,$4),geo_region_code=COALESCE(geo_region_code,$5),geo_city=COALESCE(geo_city,$6),geo_provider=COALESCE(geo_provider,$7),geo_captured_at=COALESCE(geo_captured_at,$8) WHERE id=$1`,[id,geo.countryCode,geo.countryName,geo.region,geo.regionCode,geo.city,geo.provider,geo.capturedAt])},
 async updateInvitation(v){await pool.query("UPDATE nrr_invitations SET login_count=$2,status=$3 WHERE id=$1",[v.id,v.loginCount,v.status]);return v},
 async revokeInvitation(id){const{rowCount}=await pool.query("UPDATE nrr_invitations SET status='revoked' WHERE id=$1",[id]);return rowCount>0},
 async listInvitations(){const{rows}=await pool.query("SELECT id,language,expires_at,login_limit,login_count,status,label,created_at,created_by,approved_by FROM nrr_invitations ORDER BY created_at DESC LIMIT 500");return rows},
 async createSession(v){await pool.query("INSERT INTO nrr_sessions(id,invitation_id,language,expires_at,completed,csrf_hash,ip_hash) VALUES($1,$2,$3,$4,false,$5,$6)",[v.id,v.invitationId,v.language,v.expiresAt,v.csrfHash,v.ipHash]);return v},
 async session(id,ipHash){const{rows}=await pool.query("SELECT s.*,i.email,i.full_name,i.label FROM nrr_sessions s JOIN nrr_invitations i ON i.id=s.invitation_id WHERE s.id=$1 AND s.ip_hash=$2",[id,ipHash]);const x=rows[0];return x?{id:x.id,invitationId:x.invitation_id,language:x.language,expiresAt:x.expires_at,completed:x.completed,csrfHash:x.csrf_hash,email:x.email||'',fullName:x.full_name||x.label||''}:null},
 async rotateCsrf(id,hash){await pool.query("UPDATE nrr_sessions SET csrf_hash=$2 WHERE id=$1",[id,hash])},
 async saveResponses(id,payload){await pool.query(`INSERT INTO nrr_responses(session_id,answers) VALUES($1,$2::jsonb) ON CONFLICT(session_id) DO UPDATE SET answers=EXCLUDED.answers,updated_at=now()`,[id,JSON.stringify(payload.answers)]);},
 async responses(id){const{rows}=await pool.query("SELECT answers,updated_at FROM nrr_responses WHERE session_id=$1",[id]);return rows[0]||null},
 async completeAndArchive(id,record){const client=await pool.connect();try{await client.query('BEGIN');await client.query("UPDATE nrr_sessions SET completed=true WHERE id=$1",[id]);await client.query(`INSERT INTO nrr_reports(id,session_id,invitation_id,full_name,email,language,report_json,pdf_bytes,pdf_sha256,report_version,geo_country_code,geo_country_name,geo_region,geo_region_code,geo_city,geo_provider,geo_captured_at) SELECT $1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,i.geo_country_code,i.geo_country_name,i.geo_region,i.geo_region_code,i.geo_city,i.geo_provider,i.geo_captured_at FROM nrr_invitations i WHERE i.id=$3 ON CONFLICT(session_id) DO NOTHING`,[record.id,id,record.invitationId,record.fullName,record.email,record.language,JSON.stringify(record.report),record.pdfBytes,record.pdfSha256,record.reportVersion]);await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}},
 async reportForSession(id){const{rows}=await pool.query("SELECT * FROM nrr_reports WHERE session_id=$1",[id]);return rows[0]||null},
 async listReports(){const{rows}=await pool.query("SELECT id,full_name,email,language,geo_country_code,geo_country_name,geo_region,geo_region_code,geo_city,geo_provider,geo_captured_at,pdf_sha256,report_version,generated_at FROM nrr_reports ORDER BY generated_at DESC LIMIT 1000");return rows},
 async reportById(id){const{rows}=await pool.query("SELECT * FROM nrr_reports WHERE id=$1",[id]);return rows[0]||null},
 async resetAccess(id){const client=await pool.connect();try{await client.query('BEGIN');await client.query("DELETE FROM nrr_sessions WHERE invitation_id=$1 AND completed=false",[id]);const result=await client.query("UPDATE nrr_invitations SET login_count=0,access_ip_hash=NULL,geo_country_code=NULL,geo_country_name=NULL,geo_region=NULL,geo_region_code=NULL,geo_city=NULL,geo_provider=NULL,geo_captured_at=NULL WHERE id=$1 AND status='active'",[id]);await client.query('COMMIT');return result.rowCount>0}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
};
