import express from "express";import helmet from "helmet";import cookieParser from "cookie-parser";import{rateLimit}from"express-rate-limit";import{randomToken,sha256,sessionCookieOptions}from"./security.js";import{store}from"./store.js";
const app=express();app.use(helmet());app.use(express.json({limit:"32kb"}));app.use(cookieParser());app.use("/api/",rateLimit({windowMs:60_000,limit:60,standardHeaders:"draft-8",legacyHeaders:false}));
const ADMIN=process.env.NEXTGEN_ADMIN_KEY;
function admin(req,res,next){if(!ADMIN||req.get("x-nextgen-admin-key")!==ADMIN)return res.status(403).json({error:"forbidden"});next()}
function current(req){const s=store.session(req.cookies.ng_session);return s&&new Date(s.expiresAt)>new Date()?s:null}
app.post("/api/admin/invitations",admin,(req,res)=>{const token=randomToken(),id=randomToken(12),now=new Date(),expires=new Date(req.body.expiresAt);if(!["en","cs"].includes(req.body.language)||!(expires>now))return res.status(400).json({error:"invalid invitation"});store.createInvitation({id,tokenHash:sha256(token),language:req.body.language,expiresAt:expires.toISOString(),loginLimit:req.body.loginLimit??null,loginCount:0,status:"active",createdAt:now.toISOString(),label:req.body.label||null});res.status(201).json({id,token,language:req.body.language,expiresAt:expires.toISOString()})});
app.post("/api/invitations/redeem",(req,res)=>{const inv=store.invitationByHash(sha256(String(req.body.token||"")));if(!inv||inv.status!=="active"||new Date(inv.expiresAt)<=new Date())return res.status(403).json({error:"invalid_or_expired"});if(inv.loginLimit!==null&&inv.loginCount>=inv.loginLimit)return res.status(403).json({error:"login_limit"});inv.loginCount++;store.updateInvitation(inv);const id=randomToken(24),expiresAt=new Date(Date.now()+2*60*60*1000).toISOString();store.createSession({id,invitationId:inv.id,language:inv.language,expiresAt,completed:false});res.cookie("ng_session",id,sessionCookieOptions()).json({language:inv.language,expiresAt})});
app.get("/api/session",(req,res)=>{const s=current(req);if(!s)return res.status(401).json({error:"unauthorized"});res.json({language:s.language,completed:s.completed,responses:store.responses(s.id)?.answers||{}})});
app.put("/api/responses",(req,res)=>{const s=current(req);if(!s)return res.status(401).json({error:"unauthorized"});const answers=req.body.answers||{};for(const[k,v]of Object.entries(answers)){if(!/^NRR-Q(0[1-9]|[1-3][0-9]|4[0-8])$/.test(k)||![1,2,3,4,5,"dk","na"].includes(v))return res.status(400).json({error:"invalid_response"})}store.saveResponses(s.id,{answers});res.json({ok:true})});
app.post("/api/complete",(req,res)=>{const s=current(req);if(!s)return res.status(401).json({error:"unauthorized"});const a=store.responses(s.id)?.answers||{};if(Object.keys(a).length!==48)return res.status(400).json({error:"incomplete"});s.completed=true;res.json({ok:true})});
app.get("/health",(req,res)=>res.json({ok:true,service:"nextgenreview"}));
const port=Number(process.env.PORT||3001);app.listen(port,()=>console.log("NextGen server listening",port));
