import React,{useEffect,useState} from 'react';
const copy={en:{download:'Download confidential PDF',review:'Review responses',loading:'Preparing your confidential report…',error:'Your report could not be loaded. Please retry. If your session has expired, reopen your invitation.',retry:'Retry',note:'Cover plus 17 numbered pages. Your answers, findings and next actions are reflected throughout the report.',unscored:'Unscored',notes:'Notes / agreed next step:'},cs:{download:'Stáhnout důvěrný report v PDF',review:'Zkontrolovat odpovědi',loading:'Připravujeme váš důvěrný report…',error:'Report se nepodařilo načíst. Zkuste to znovu. Pokud relace vypršela, znovu otevřete pozvánku.',retry:'Zkusit znovu',note:'Obálka a 17 číslovaných stran. Report obsahuje vaše odpovědi, zjištění a další kroky.',unscored:'Bez hodnocení',notes:'Poznámky / dohodnutý další krok:'},de:{download:'Vertraulichen PDF-Bericht herunterladen',review:'Antworten prüfen',loading:'Ihr vertraulicher Bericht wird vorbereitet…',error:'Ihr Bericht konnte nicht geladen werden. Bitte versuchen Sie es erneut. Bei abgelaufener Sitzung öffnen Sie Ihre Einladung erneut.',retry:'Erneut versuchen',note:'Deckblatt und 17 nummerierte Seiten. Ihre Antworten, Befunde und nächsten Schritte sind im gesamten Bericht berücksichtigt.',unscored:'Unbewertet',notes:'Notizen / vereinbarter nächster Schritt:'}};
const trademark={en:'NextGen Readiness Review™ is a trademark of Adamas Advisors · © 2026 Adamas Advisors',cs:'NextGen Readiness Review™ je ochranná známka společnosti Adamas Advisors · © 2026 Adamas Advisors',de:'NextGen Readiness Review™ ist eine Marke von Adamas Advisors · © 2026 Adamas Advisors'};
const colours=['#b44f44','#d9a43d','#3e8056'];
function Score({level,t}){return <span className="live-score"><span>{colours.map((c,i)=><i key={c} style={{background:level===i+1?c:'#c7cac3'}}/>)}</span><b>{level?level+'/3':t.unscored}</b></span>}
function Portrait({page,t}){const points=page.points.map((s,i)=>{const a=Math.PI/2-i*2*Math.PI/24,r=100*(s.level||0)/3;return s.level?{x:150+r*Math.cos(a),y:150-r*Math.sin(a),level:s.level}:null});return <><svg viewBox="0 0 300 300" className="live-portrait" role="img" aria-label={page.title}>{[1,2,3].map(k=><circle key={k} cx="150" cy="150" r={100*k/3} fill="none" stroke="#d8d0c1"/>)}{points.map((p,i)=>p&&<g key={i}>{points[(i+1)%24]&&<line x1={p.x} y1={p.y} x2={points[(i+1)%24].x} y2={points[(i+1)%24].y} stroke="#0f3b2e"/>}<circle cx={p.x} cy={p.y} r="3" fill={colours[p.level-1]}/></g>)}</svg><div className="live-dimensions">{page.dimensions.map(d=><article key={d.name}><h3>{d.name}</h3><Score level={d.level} t={t}/><p>{d.summary}</p></article>)}</div></>}
export function LiveReport({language,onReview}){
 const [report,setReport]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[downloading,setDownloading]=useState(false);const t=copy[language];
 useEffect(()=>{const controller=new AbortController();setReport(null);setError(false);fetch('/api/report?language='+encodeURIComponent(language),{credentials:'include',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('report_unavailable');const data=await r.json();if(data.language!==language||data.pages.length!==18)throw Error('invalid_report');return data}).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>controller.abort()},[language,retry]);
 async function download(){setDownloading(true);setError(false);try{const response=await fetch('/api/report.pdf?language='+encodeURIComponent(language),{credentials:'include'});if(!response.ok||!response.headers.get('Content-Type')?.includes('application/pdf'))throw Error('report_unavailable');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='NextGen_Readiness_Report_'+language.toUpperCase()+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError(true)}finally{setDownloading(false)}}
 if(!t)throw Error('unsupported_report_language');
 return <main className="acr-stage live-report" lang={language}><div className="live-report-toolbar"><button className="acr-primary" disabled={!report||downloading} onClick={download}>{t.download}</button><button className="acr-retake" onClick={onReview}>{t.review}</button><p>{t.note}</p></div>{error&&<div role="alert"><p>{t.error}</p><button onClick={()=>setRetry(n=>n+1)}>{t.retry}</button></div>}{!report&&!error&&<p role="status">{t.loading}</p>}{report?.pages.filter(page=>[3,13,14].includes(page.number)).map(page=><section className="live-report-page" key={page.number}><header>{page.number>0&&<span>{String(page.number).padStart(2,'0')}</span>}<h1>{page.title}</h1></header>{page.subtitle&&<p className="live-subtitle">{page.subtitle}</p>}{page.number===0&&<><p>{report.date}</p><img className="live-cover" src="/report-assets/cover.jpg" alt=""/></>}{page.number===3&&<Portrait page={page} t={t}/>}<div className="live-page-content">{page.items.map((item,i)=>item.type==='score'?<p key={i}><Score level={item.level} t={t}/> <span>{item.text}</span></p>:item.type==='field'?<p key={i}><strong>{item.label}: </strong>{item.text}</p>:['heading','kicker'].includes(item.type)?<h3 className={item.type==='kicker'?'live-kicker':''} key={i}>{item.text}{page.scores?.find(s=>s.label===item.text)&&<Score level={page.scores.find(s=>s.label===item.text).level} t={t}/>}</h3>:<p key={i}>{item.text}</p>)}</div>{page.number>0&&page.number!==1&&page.number!==3&&<div className="live-notes">{t.notes}</div>}<footer>ADAMAS ADVISORS {page.number>0&&<span>{page.number}</span>}<small>{trademark[language]}</small></footer></section>)}</main>
}
