import {reviewText,ReviewTrademarkNotice} from './ReviewText.jsx';
import React,{useEffect,useState} from 'react';
const copy={en:{download:'Download confidential PDF',review:'Review responses',loading:'Preparing your confidential report…',error:'Your report could not be loaded. Please retry. If your session has expired, reopen your invitation.',retry:'Retry',note:'Your personalised interpretation and practical next steps are included in the extended report.',unscored:'Unscored',notes:'Notes / agreed next step:'},cs:{download:'Stáhnout důvěrný report v PDF',review:'Zkontrolovat odpovědi',loading:'Připravujeme váš důvěrný report…',error:'Report se nepodařilo načíst. Zkuste to znovu. Pokud relace vypršela, znovu otevřete pozvánku.',retry:'Zkusit znovu',note:'Rozšířený report obsahuje individuální výklad a praktické kroky.',unscored:'Bez hodnocení',notes:'Poznámky / dohodnutý další krok:'},de:{download:'Vertraulichen PDF-Bericht herunterladen',review:'Antworten prüfen',loading:'Ihr vertraulicher Bericht wird vorbereitet…',error:'Ihr Bericht konnte nicht geladen werden. Bitte versuchen Sie es erneut. Bei abgelaufener Sitzung öffnen Sie Ihre Einladung erneut.',retry:'Erneut versuchen',note:'Der erweiterte Bericht enthält Ihre individuelle Einordnung und praktische Schritte.',unscored:'Unbewertet',notes:'Notizen / vereinbarter nächster Schritt:'}};
const trademark={en:'NextGen Readiness Review™ is a trademark of Adamas Advisors · © 2026 Adamas Advisors',cs:'NextGen Readiness Review™ je ochranná známka společnosti Adamas Advisors · © 2026 Adamas Advisors',de:'NextGen Readiness Review™ ist eine Marke von Adamas Advisors · © 2026 Adamas Advisors'};
const colours=['#b44f44','#d9a43d','#3e8056'];
function Score({level,t}){return <span className="live-score"><span>{reviewText(colours.map((c,i)=><i key={c} style={{background:level===i+1?c:'#c7cac3'}}/>))}</span><b>{reviewText(level?level+'/3':t.unscored)}</b></span>}
function Portrait({page,t,compass}){
 if(!compass?.image?.startsWith('data:image/png;base64,')||!compass.sha256)throw Error('canonical_compass_missing');
 return <><img className="live-portrait canonical-compass" src={compass.image} width={compass.width} height={compass.height} style={{maxWidth:'100%',height:'auto',display:'block',margin:'0 auto'}} data-compass-sha256={compass.sha256} data-compass-version={compass.version} alt={page.dimensions.map(d=>d.name+': '+(d.level?d.level+'/3':t.unscored)).join('; ')} /><div className="live-dimensions">{reviewText(page.dimensions.map(d=><article key={d.name}><h3>{reviewText(d.name)}</h3><Score level={d.level} t={t}/><p>{reviewText(d.summary)}</p></article>))}</div></>;
}
export function LiveReport({language,onReview,qa=false}){
 const [report,setReport]=useState(null),[error,setError]=useState(false),[retry,setRetry]=useState(0),[downloading,setDownloading]=useState(false);const t=copy[language];
 useEffect(()=>{const controller=new AbortController();setReport(null);setError(false);fetch((qa?'/qa/specimen.json?language=':'/api/report?language=')+encodeURIComponent(language),{credentials:'include',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('report_unavailable');const data=await r.json();if(data.language!==language||data.pages.length<18||data.pages.some((p,i)=>p.number!==i))throw Error('invalid_report');return data}).then(setReport).catch(e=>{if(e.name!=='AbortError')setError(true)});return()=>controller.abort()},[language,retry]);
 async function download(){setDownloading(true);setError(false);try{const response=await fetch((qa?'/qa/specimen.pdf?language=':'/api/report.pdf?language=')+encodeURIComponent(language),{credentials:'include'});if(!response.ok||!response.headers.get('Content-Type')?.includes('application/pdf'))throw Error('report_unavailable');const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download='NextGen_Readiness_Report_'+language.toUpperCase()+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{setError(true)}finally{setDownloading(false)}}
 if(!t)throw Error('unsupported_report_language');
 return <main className="acr-stage live-report" lang={language}><div className="live-report-toolbar"><button className="acr-primary" disabled={!report||downloading} onClick={download}>{reviewText(t.download)}</button><button className="acr-retake" onClick={onReview}>{reviewText(t.review)}</button><p>{reviewText(t.note)}</p></div>{reviewText(error&&<div role="alert"><p>{reviewText(t.error)}</p><button onClick={()=>setRetry(n=>n+1)}>{reviewText(t.retry)}</button></div>)}{reviewText(!report&&!error&&<p role="status">{reviewText(t.loading)}</p>)}{reviewText(report?.pages.map(page=><section className="live-report-page" key={page.number}><header>{reviewText(page.number>0&&<span>{reviewText(String(page.number).padStart(2,'0'))}</span>)}<h1>{reviewText(page.title)}</h1></header>{reviewText(page.subtitle&&<p className="live-subtitle">{reviewText(page.subtitle)}</p>)}{reviewText(page.number===0&&<><p>{reviewText(report.date)}</p><img className="live-cover" src="/report-assets/cover.jpg" alt=""/></>)}{reviewText(page.number===3&&<Portrait page={page} t={t} compass={report.compass}/>)}<div className="live-page-content">{reviewText(page.items.map((item,i)=>item.type==='score'?<p key={i}><Score level={item.level} t={t}/> <span>{reviewText(item.text)}</span></p>:item.type==='field'?<p key={i}><strong>{reviewText(item.label)}: </strong>{reviewText(item.text)}</p>:['heading','kicker'].includes(item.type)?<h3 className={item.type==='kicker'?'live-kicker':''} key={i}>{reviewText(item.text)}{reviewText(page.scores?.find(s=>s.label===item.text)&&<Score level={page.scores.find(s=>s.label===item.text).level} t={t}/>)}</h3>:<p key={i}>{reviewText(item.text)}</p>))}</div>{reviewText(page.number>0&&page.number!==1&&page.number!==3&&<div className="live-notes">{reviewText(t.notes)}</div>)}<footer>ADAMAS ADVISORS {reviewText(page.number>0&&<span>{reviewText(page.number)}</span>)}<small>{reviewText(trademark[language])}</small></footer></section>))}</main>
}
