import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import express from 'express';import {PDFDocument} from 'pdf-lib';
import {analyse,localise,contract,content,translator,validateAnswers} from '../reports/model.js';import {buildReport} from '../reports/pages.js';import {renderPDF} from '../reports/pdf.js';import {installReportRoutes} from '../reports/routes.js';
const fixtures=JSON.parse(fs.readFileSync(new URL('./fixtures/report-model.json',import.meta.url),'utf8'));
const all=v=>Object.fromEntries(Array.from({length:48},(_,i)=>['NRR-Q'+String(i+1).padStart(2,'0'),v]));
test('shared scoring, findings, targeted actions and priorities match the approved Python source',()=>{
 for(const f of fixtures){const m=analyse(f.answers),e=f.expected;for(let i=0;i<24;i++)for(const k of ['status','level','mean','finding','action','progress','trace'])assert.deepEqual(m.subs[i][k],e.subs[i][k],k);for(let i=0;i<6;i++)for(const k of ['status','mean','summary','visibility'])assert.deepEqual(m.dims[i][k],e.dims[i][k],k);assert.deepEqual(m.priorities.map(s=>s.id),e.priorities.map(s=>s.id));assert.deepEqual(m.strengths.map(s=>s.id),e.strengths.map(s=>s.id));assert.deepEqual(m.signals,e.signals);}
});
test('every pair combination has complete interpretation in every released language',()=>{
 for(const row of content.subdimensions)for(const x of [1,2,3,4,5,'dk','na',undefined])for(const y of [1,2,3,4,5,'dk','na',undefined]){const a=all(3);for(const [q,v] of [[row.questions[0],x],[row.questions[1],y]])v===undefined?delete a[q]:a[q]=v;const model=analyse(a);for(const lang of contract.supported_languages){const s=localise(model,lang).subs.find(s=>s.id===row.id);for(const key of contract.required_interpretation_fields)assert.ok(s[key],lang+':'+row.id+':'+key);}}
});
test('strict language and input release gates',()=>{assert.throws(()=>translator('fr'),/unsupported_language/);assert.throws(()=>validateAnswers({...all(3),'NRR-Q49':4}),/invalid/);assert.throws(()=>validateAnswers(all(true)),/invalid/);assert.throws(()=>buildReport({},'en'),/incomplete/);assert.ok(analyse(all('dk')).subs.every(s=>s.level===null));assert.ok(analyse(all('na')).subs.every(s=>s.level===null));});
test('complete answers produce 23 readable pages in every language',async()=>{
 for(const f of fixtures)for(const lang of contract.supported_languages){const report=buildReport(f.answers,lang);assert.equal(report.pages.length,23);const text=JSON.stringify(report);assert.ok(!text.includes('{{'));assert.ok(!text.includes('fictional'));assert.equal(report.pages.slice(6,12).flatMap(p=>p.items.filter(i=>i.type==='field'&&/Q\d/.test(i.label))).length,24);const result=await renderPDF(report);assert.equal((await PDFDocument.load(result.bytes)).getPageCount(),23);assert.ok(result.bounds.every(b=>b.bottom>=120&&b.fontSize>=8.1));}
});
test('actual completed-session endpoints protect reports and honour language selection',async()=>{
 const app=express();const sessions={done:{id:'one',completed:true,language:'cs'},other:{id:'two',completed:true,language:'de'},partial:{id:'partial',completed:false,language:'en'}};const calls=[];
 installReportRoutes(app,{current:async req=>sessions[req.get('x-test-session')],store:{responses:async id=>{calls.push(id);return {answers:all(id==='two'?5:2)}}}});
 const server=app.listen(0);await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port;
 try{for(const path of ['/api/report','/api/report.pdf']){let r=await fetch(origin+path);assert.equal(r.status,401);assert.match(r.headers.get('cache-control'),/no-store/);r=await fetch(origin+path,{headers:{'x-test-session':'partial'}});assert.equal(r.status,409);}assert.equal(calls.length,0);assert.equal((await fetch(origin+'/api/report?language=fr',{headers:{'x-test-session':'done'}})).status,400);
 for(const lang of contract.supported_languages){const r=await fetch(origin+'/api/report?language='+lang,{headers:{'x-test-session':'done'}});assert.equal(r.status,200);const data=await r.json();assert.equal(data.language,lang);assert.equal(data.contentVersion,contract.content_version);const pdf=await fetch(origin+'/api/report.pdf?language='+lang,{headers:{'x-test-session':'done'}});assert.equal(pdf.status,200);assert.match(pdf.headers.get('content-type'),/application\/pdf/);assert.match(pdf.headers.get('content-disposition'),new RegExp(lang.toUpperCase()));assert.equal((await PDFDocument.load(await pdf.arrayBuffer())).getPageCount(),18);}
 const own=await(await fetch(origin+'/api/report',{headers:{'x-test-session':'other'}})).json();assert.equal(own.language,'de');assert.equal(own.pages[3].points[0].level,3);assert.equal(calls.at(-1),'two');
 }finally{await new Promise(r=>server.close(r));}
});
